### PR TITLE
Expose new wrappers without underscores for compatibility with IBM fortran compiler

### PR DESCRIPTION
**Pull request by 1sbeller**

### CODE REVIEW

**Comment by 1sbeller** [comment]
Hi,
Is the github repository still alive?
Stephen

**Comment by ghost** [comment]
Hi,
I was responsible for this repository in the past. I deleted the associated
github account some time ago. I don't think this repository is actively
maintained, but there are ASDF users that may appreciate your pull request.
James

**Comment by 1sbeller** [comment]
Hi James,
Thank you for your reply. I understand you are not responsible for this repository anymore. 
Could you tell me who is responsible for it now?
Thanks again,
Stephen

**Comment by ghost** [comment]
I don't know, but would say no one is responsible for this repository now.
Lion Krischer may have administrative access to the organization and if so
he can assign someone (if they were interested) to take charge of this
repository. I would get in touch with him especially if you are interested
in making active contributions.

**Pull request merged**
